//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class divanshifoodsnroomsEntities : DbContext
    {
        public divanshifoodsnroomsEntities()
            : base("name=divanshifoodsnroomsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_M_CONTACTUS> TBL_M_CONTACTUS { get; set; }
        public virtual DbSet<TBL_M_SUBSCRIPTIONS> TBL_M_SUBSCRIPTIONS { get; set; }
        public virtual DbSet<TBL_M_USER> TBL_M_USER { get; set; }
    }
}
