//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_M_USER
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string CheckedIn { get; set; }
        public string CheckedOut { get; set; }
        public int Room { get; set; }
        public Nullable<int> Adult { get; set; }
        public Nullable<int> Children { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
